### ISSUE TITLE
Handle of equals(:array[element])

### ISSUE THREAD

**Issue by sartatpdev999** [cangelis/simple-validator#15]
Hi. It's unavailable to handle POST array variable in equal rule. The following rules doesn't work:
```
'user[password]' => [
  'required',
  'min_length(6)',
],
'user[password_confirm]' => [
   'required',
   'equals(:user[password])',
],
```
Looks like regular expression in ```./simple-validator/src/SimpleValidator/Validator.php``` at line ```195``` should be improve.

My temporary dummy solution:
```
if (preg_match("#^:([\[\]a-zA-Z0-9_]+)$#", $param, $param_type)) {
```
Let me know if i'm wrong. Thanks

**Comment by cangelis** [comment]
How is your POST input look like? Can you please `var_dump()` your POST input?

**Comment by sartatpdev999** [comment]
Yes. Of course

```
array(2) {
  ["user[password]"]=>
  string(6) "123456"
  ["user[password_confirm]"]=>
  string(6) "123456"
}
```

**Comment by cangelis** [comment]
87aabf6a667cbea92efc2f88e2eea2a4121a6472 should fix it.

**Comment by aaaatpdev** [comment]
Thanks!

**Comment by aaaatpdev** [comment]
This commit doesn't solve it. The POST dump above isn't dump of a valid POST array. The valid dump of a GET/POST array looks like:

```
array(1) {
  ["test"]=>
  array(2) {
    ["a"]=>
    string(3) "123"
    ["b"]=>
    array(2) {
      ["c"]=>
      string(3) "456"
      ["d"]=>
      string(3) "789"
    }
  }
}
```
So the valid POST array dump above is:
```
array(1) {
  ["user"]=>
  array(2) {
    ["password"]=>
    string(6) "123456"
    ["password_confirm"]=>
    string(6) "123456"
  }
}
```
This simple code demonstrates the problem:

```
$validatorRules = [
  'test[a]' => [
    'required',
  ],
  'test[b]' => [
    'required',
  ],
];

$validator = SimpleValidator\Validator::validate($_GET, $validatorRules);
if (!$validator->isSuccess()) {
  var_dump($validator->getErrors());
}

// And go to http://your.domain/path/to/index.php?test[a]=123&test[b]=456

/*

Will output:

array(2) {
  [0]=>
  string(25) "test[a] field is required"
  [1]=>
  string(25) "test[b] field is required"
}

*/

```

I guess that rules for array's validation should be something like `array.key`. And the validator should parse input names with dots and translate it to arrays.

By the way this trick can temporary solve the problem (it will work only with square brackets in the regular expression):
```
// Set $_POST arrays to $_POST['value[key]'] (will work only for one-dimensional arrays)
foreach ($_POST as $key => $value) {
  if (is_array($value)) {
    foreach ($value as $reqKey => $reqValue) {
      $_POST[$key . '[' . $reqKey . ']'] = $reqValue;
    }
  }
}
```
